name: stellar_flutter_sdk
description: A stellar blockchain sdk that query's horizon, build, signs and submits transactions to the stellar network.
version: 1.1.9
homepage: https://github.com/Soneso/stellar_flutter_sdk

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  convert: ^2.1.1
  crypto: ^2.1.3
  eventsource: ^0.2.2
  fixnum: ^0.10.11
  http: ^0.12.0+3
  tweetnacl: ^0.3.2
  collection: ^1.14.0
  toml: ^0.6.0
  pointycastle: ^1.0.0
  unorm_dart: ^0.1.2
  decimal: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
